### ISSUE TITLE
Show audit logs in each server individually instead of in the admin area.

### ISSUE THREAD

**Issue by Synkstar** [Tdash2/Pterodactyl_audit_logs#2]
There is a paid addon for pterodactyl that does this. Ill probably be attempting to do this myself when I get the time though but this basically has everything you need. All you would really have to do is put it in the server and filter by server id so it only shows the logs for the specific server.
Looks like this:
![image](https://user-images.githubusercontent.com/26175394/145734695-e30be3d5-011e-428c-898e-594d7d014fdd.png)

**Comment by Tdash2** [comment]
I think I will implement that soon. Most likely I will not have the delete as this is logs and you should not be able to delete logs.

**Comment by Synkstar** [comment]
Yeah idk why they would have the ability to delete logs that seems kind of strange.

**Comment by Synkstar** [comment]
Another thing I probably wish pterodactyl panel had built in was a real crash detector that used query protocols. Say a2s_info for source engine and the query for minecraft to determine if the server is frozen built into the panel. Ive made something before that does this but it used the api and an external program to check. But to do this you would need it to also be on wings so it sends to the server directly because some people have networks that do caching of these to lessen ddos attack vectors. Like otherwise a gmod server for example can become frozen and it would stay frozen unless you manually kill and start it. Games like rust also use a2s_info aswell.

**Comment by Tdash2** [comment]
Done!

> There is a paid addon for pterodactyl that does this. Ill probably be attempting to do this myself when I get the time though but this basically has everything you need. All you would really have to do is put it in the server and filter by server id so it only shows the logs for the specific server. Looks like this: ![image](https://user-images.githubusercontent.com/26175394/145734695-e30be3d5-011e-428c-898e-594d7d014fdd.png)
