### ISSUE TITLE
Issue installing the addon

### ISSUE THREAD

**Issue by scalda** [Tdash2/Pterodactyl_audit_logs#3]
HI,

i have recently come across your addon, and this will be the first addon i have installed, i have nodejs14 installed and have run the yarn commands but i am getting this error and for the life of me i can't work it out

[log](https://gist.github.com/scalda/d8ce33d848e75e0346b142d2cbbde03f)

any help would be great

**Comment by Tdash2** [comment]
Try deleting your node_modules folder, do yarn again and then finally yarn build:production
