### ISSUE TITLE
audit log button not showing

### ISSUE THREAD

**Issue by Shersha01** [Tdash2/Pterodactyl_audit_logs#6]
Hey audit log button not showing idk why. It is showing if go to url/admin/logs

**Comment by Tdash2** [comment]
does it show up on the client side?

**Comment by Shersha01** [comment]
> does it show up on the client side?
Nope

**Comment by Tdash2** [comment]
Try to upload the files manually from [here  ](https://github.com/Tdash2/Pterodactyl_audit_logs/releases/download/2.1.0/logs.zip) then upload them and make sure that it overwrites the original files. Then build your panel

**Comment by Shersha01** [comment]
> Try to upload the files manually from [here ](https://github.com/Tdash2/Pterodactyl_audit_logs/releases/download/2.1.0/logs.zip) then upload them and make sure that it overwrites the original files. Then build your panel

Will do in 30 mins
